# JSON exercise

Download the data from [**here**](https://drive.google.com/file/d/1DGaX5AVfYhmWeb15lI-MzUbSKTYSz9fQ/view?usp=sharing) and answer following questions:
1. Find the 10 countries with most projects - **China**
2. What are top 10 sectors with projects?
   1. Other social services                                       106
   2. Central government administration                            82
   3. Sub-national government administration                       75
   4. General agriculture, fishing and forestry sector             65
   5. Health                                                       63
   6. General public administration sector                         51
   7. Rural and Inter-Urban Roads and Highways                     44
   8. General water, sanitation and flood protection sector        39
   9. Agricultural extension and research                          38
   10. Public administration- Agriculture, fishing and forestry     36
4. Find the top 10 major project themes (using column 'mjtheme_namecode')
5. In 3. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [57]:
import pandas as pd

In [58]:
data = pd.read_json('world_bank_projects.json')

In [59]:
data

,sector,supplementprojectflg,projectfinancialtype,prodline,mjtheme,idacommamt,impagency,project_name,mjthemecode,closingdate,...,majorsector_percent,board_approval_month,theme_namecode,countryname,url,source,projectstatusdisplay,ibrdcommamt,sector_namecode,_id
0,"[{'Name': 'Primary education'}, {'Name': 'Seco...",N,IDA,PE,[Human development],130000000,MINISTRY OF EDUCATION,Ethiopia General Education Quality Improvement...,"8,11",2018-07-07T00:00:00Z,...,"[{'Percent': 46, 'Name': 'Education'}, {'Perce...",November,"[{'code': '65', 'name': 'Education for all'}]",Federal Democratic Republic of Ethiopia,http://www.worldbank.org/projects/P129828/ethi...,IBRD,Active,0,"[{'code': 'EP', 'name': 'Primary education'}, ...",{'$oid': '52b213b38594d8a2be17c780'}
1,[{'Name': 'Public administration- Other social...,N,OTHER,RE,"[Economic management, Social protection and ri...",0,MINISTRY OF FINANCE,TN: DTF Social Protection Reforms Support,"1,6",NaN,...,"[{'Percent': 70, 'Name': 'Public Administratio...",November,"[{'code': '24', 'name': 'Other economic manage...",Republic of Tunisia,http://www.worldbank.org/projects/P144674?lang=en,IBRD,Active,0,"[{'code': 'BS', 'name': 'Public administration...",{'$oid': '52b213b38594d8a2be17c781'}
2,[{'Name': 'Rural and Inter-Urban Roads and Hig...,Y,IDA,PE,"[Trade and integration, Public sector governan...",6060000,MINISTRY OF TRANSPORT AND COMMUNICATIONS,Tuvalu Aviation Investment Project - Additiona...,"5,2,11,6",NaN,...,"[{'Percent': 100, 'Name': 'Transportation'}]",November,"[{'code': '47', 'name': 'Regional integration'...",Tuvalu,http://www.worldbank.org/projects/P145310?lang=en,IBRD,Active,0,"[{'code': 'TI', 'name': 'Rural and Inter-Urban...",{'$oid': '52b213b38594d8a2be17c782'}
3,[{'Name': 'Other social services'}],N,OTHER,RE,"[Social dev/gender/inclusion, Social dev/gende...",0,LABOR INTENSIVE PUBLIC WORKS PROJECT PMU,Gov't and Civil Society Organization Partnership,"7,7",NaN,...,"[{'Percent': 100, 'Name': 'Health and other so...",October,"[{'code': '57', 'name': 'Participation and civ...",Republic of Yemen,http://www.worldbank.org/projects/P144665?lang=en,IBRD,Active,0,"[{'code': 'JB', 'name': 'Other social services'}]",{'$oid': '52b213b38594d8a2be17c783'}
4,[{'Name': 'General industry and trade sector'}...,N,IDA,PE,"[Trade and integration, Financial and private ...",13100000,MINISTRY OF TRADE AND INDUSTRY,Second Private Sector Competitiveness and Econ...,"5,4",2019-04-30T00:00:00Z,...,"[{'Percent': 50, 'Name': 'Industry and trade'}...",October,"[{'code': '45', 'name': 'Export development an...",Kingdom of Lesotho,http://www.worldbank.org/projects/P144933/seco...,IBRD,Active,0,"[{'code': 'YZ', 'name': 'General industry and ...",{'$oid': '52b213b38594d8a2be17c784'}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,"[{'Name': 'General agriculture, fishing and fo...",N,OTHER,RE,"[Financial and private sector development, Soc...",0,THE COMPETITIVENESS COMPANY,Technological Scale Up for Youth-led Urban Orn...,"4,7",2013-08-31T00:00:00Z,...,"[{'Percent': 50, 'Name': 'Agriculture, fishing...",August,"[{'code': '40', 'name': 'Regulation and compet...",Jamaica,http://www.worldbank.org/projects/P127299/tech...,IBRD,Closed,0,"[{'code': 'AZ', 'name': 'General agriculture, ...",{'$oid': '52b213b38594d8a2be17c96f'}
496,[{'Name': 'Central government administration'}...,N,IDA,PE,"[Human development, Trade and integration, Pub...",20000000,MINISTRY OF FINANCE,Lao Eight Poverty Reduction Support,"8,5,2,8",2012-12-31T00:00:00Z,...,"[{'Percent': 36, 'Name': 'Public Administratio...",August,"[{'code': '63', 'name': 'Child health'}, {'cod...",Lao People's Democratic Republic,http://www.worldbank.org/projects/P125298/lao-...,IBRD,Closed,0,"[{'code': 'BC', 'name': 'Central government ad...",{'$oid': '52b213b38594d8a2be17c970'}
497,"[{'Name': 'Irrigation and drainage'}, {'Name':...",N,OTHER,RE,[Rural development],0,MINISTRY OF AGRICULTURE AND PRODUCER ORGANISAT...,Second Emergency Agricultural Productivity Sup...,"10,6",2014-12-31T00:00:00Z,...,"[{'Percent': 40, 'Name': 'Agriculture, fishing...",August,"[{'code': '91', 'name': 'Global food crisis re...",Republic of Guinea,http://www.worldbank.org/projects/P128309/seco...,IBRD,Active,0,"[{'code': 'AI', 'name': 'Irrigation and draina...",{'$oid': '52b213b38594d8a2be17c971'}
498,[{'Name': 'Agricultural extension and research...,N,IBRD,PE,"[Rural development, Rural development, Rural d...",0,INDONESIAN AGENCY FOR AGRICULTURAL RESEARCH AN...,Sustainable Management of Agricultural Researc...,"10,10,10",2017-09-30T00:00:00Z,...,"[{'Percent': 80, 'Name': 'Agriculture, fishing...",August,"[{'code': '78', 'name': 'Rural services and in...",Republic of Indonesia,http://www.worldbank.org/projects/P117243/sust...,IBRD,Active,80000000,"[{'code': 'AB', 'name': 'Agricultural extensio...",{'$oid': '52b213b38594d8a2be17c972'}
499,"[{'Name': 'Urban Transport'}, {'Name': 'Public...",N,IDA,PE,"[Urban development, Human development, Trade a...",300000000,MINISTRY OF ROADS,KENYA: NATIONAL URBAN TRANSPORT IMPROVEMENT PR...,"9,8,5,4",2018-12-31T00:00:00Z,...,"[{'Percent': 79, 'Name': 'Transportation'}, {'...",August,"[{'code': '73', 'name': 'Municipal governance ...",Republic of Kenya,http://www.worldbank.org/projects/P126321/keny...,IBRD,Active,0,"[{'code': 'TC', 'name': 'Urban Transport'}, {'...",{'$oid': '52b213b38594d8a2be17c973'}

In [75]:
grouped_by_country_count = data.groupby('countryname').count()

In [76]:
sorted_data = grouped_by_country_count.sort_values(by='project_name', ascending=False)

In [77]:
sorted_data

,sector,supplementprojectflg,projectfinancialtype,prodline,mjtheme,idacommamt,impagency,project_name,mjthemecode,closingdate,...,sector3,majorsector_percent,board_approval_month,theme_namecode,url,source,projectstatusdisplay,ibrdcommamt,sector_namecode,_id
countryname,,,,,,,,,,,,,,,,,,,,,
People's Republic of China,19,19,19,19,17,19,19,19,19,16,...,11,19,19,17,19,19,19,19,19,19
Republic of Indonesia,19,19,19,19,19,19,19,19,19,15,...,10,19,19,19,19,19,19,19,19,19
Socialist Republic of Vietnam,17,16,17,17,17,17,17,17,17,14,...,10,17,17,17,17,17,17,17,17,17
Republic of India,16,16,16,16,16,16,15,16,16,13,...,9,16,16,16,16,16,16,16,16,16
Republic of Yemen,13,13,13,13,13,13,13,13,13,8,...,4,13,13,13,13,13,13,13,13,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Antigua and Barbuda,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Republic of Kiribati,1,1,1,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1
Republic of Serbia,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Republic of Poland,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Republic of Zimbabwe,1,1,1,1,1,1,1,1,1,0,...,0,1,1,1,1,1,1,1,1,1

In [94]:
pd.json_normalize(data=data, record_path='sector', meta=['Name'])

TypeError: string indices must be integers

In [103]:
# Re-importing the JSON module and reloading the data due to the reset of the code execution environment
import json

# Re-load the JSON data
file_path = 'world_bank_projects.json'
with open(file_path, 'r') as file:
    data = json.load(file)

# Importing pandas for data manipulation
import pandas as pd

# Creating a DataFrame for sectors
sectors_data = pd.DataFrame()

sector_list = []

for project in data:
    if 'sector' in project:
        for sector in project['sector']:
            sector['project_id'] = project['id']
            sector_list.append(sector)

# Converting the list to a DataFrame
sectors_data = pd.DataFrame(sector_list)

# Grouping by sector name and counting the number of projects in each sector
top_sectors = sectors_data.groupby('Name').size().sort_values(ascending=False).head(10)

top_sectors

Name
Other social services                                       106
Central government administration                            82
Sub-national government administration                       75
General agriculture, fishing and forestry sector             65
Health                                                       63
General public administration sector                         51
Rural and Inter-Urban Roads and Highways                     44
General water, sanitation and flood protection sector        39
Agricultural extension and research                          38
Public administration- Agriculture, fishing and forestry     36
dtype: int64

In [105]:
grouped_by_mjtheme = data.groupby('mjtheme').count()

AttributeError: 'list' object has no attribute 'groupby'